<a href="https://colab.research.google.com/github/math288/math288.github.io/blob/main/math01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#線形代数の計算

###ベクトルの計算

In [1]:
import numpy as np
A = np.array([1,2,2]) #ベクトルなので、1次元配列で[]一つだけ
B = np.array([3,4,5])
print (A @ B)

21


###行列の足し算

In [2]:
import numpy as np

# 行列 A と B を定義します
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# 行列の足し算
C = A + B

print("行列 A:")
print(A)
print("\n行列 B:")
print(B)
print("\n行列の足し算結果 (A + B):")
print(C)

行列 A:
[[1 2]
 [3 4]]

行列 B:
[[5 6]
 [7 8]]

行列の足し算結果 (A + B):
[[ 6  8]
 [10 12]]


In [3]:
#行列AとBの定義
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6], [7, 8]])

#行列の足し算
C = A + B

print ("行列A:")
print (A)
print ("行列B:")
print (B)
print ("行列A + Bの計算結果　行列C:")
print (C)

行列A:
[[1 2]
 [3 4]]
行列B:
[[5 6]
 [7 8]]
行列A + Bの計算結果　行列C:
[[ 6  8]
 [10 12]]


###行列のスカラー倍

In [4]:
A = np.array([[1,2], [3,4]])
print (3*A)

[[ 3  6]
 [ 9 12]]


###ゼロ行列の計算

In [5]:
A = np.array([[3,5], [3,6]])
O = np.array([[0,0], [0,0]])  #ゼロ行列を定義（すべての成分がゼロの行列）
print (A + O)

[[3 5]
 [3 6]]


###行列の積

In [6]:
A = np.array([[3, 5], [8, 2]])
B = np.array([[1, 2], [3, 4]])
print (A * B) #これはアダマール積
print (A @ B) #行列の積

[[ 3 10]
 [24  8]]
[[18 26]
 [14 24]]


##射影の基本

In [7]:
import numpy as np
A = np.array([3,4])
B = np.array([4,4])
X = A @ B
Y = B @ B
print ((X/Y) * B)



[3.5 3.5]


##ベクトルの回転
ベクトルvの回転後のベクトルv'は、二次元かつ反時計回りの場合、以下のような行列をかけることで求めることができる。

$$R =\begin{pmatrix} \cos\theta & -\sin\theta \\ \sin\theta & \cos\theta \end{pmatrix}$$

この導出を行う。
x座標とy座標を持つ関数のグラフを考え、ある任意の点(a, b) をとる。
その時の点までの距離をr、角度を$\alpha$とする。
すると、 $$a = r\cos\alpha　---①$$
$$b = r\sin\alpha　---②$$
と書くことができる。
$\theta$だけ回転した後の点の座標を(a', b')とすると、
$$a' = r\cos(\alpha + \theta)$$
$$b' = r\sin(\alpha + \theta)$$
となる。
ここで**加法定理**を用いることで以下が導き出せる。
$$a'
= r\cos(\alpha + \theta)
= r(\cos\alpha \cos\theta - \sin\alpha \sin\theta)
=(r\cos\alpha) \cos\theta - (r\sin\alpha)\sin\theta$$
$$b'
= r(\sin\alpha \cos\theta + \cos\alpha \sin\theta=(r\sin\alpha)\cos\theta + (r\cos\alpha)\sin\theta $$
①と②からこれらの式は
$$a' = a\cos\theta - b\sin\theta$$
$$b' = a\sin\theta + b\cos\theta$$
よって、これらを行列とベクトルの積として、移動後のベクトルは
$$\begin{pmatrix} \cos\theta & -\sin\theta \\\sin\theta & \cos\theta\end{pmatrix} \begin{pmatrix} a \\ b\end{pmatrix}
= \begin{pmatrix}  a'\\ b'\end {pmatrix}$$
よって、導出ができた。

In [8]:
v = np.array([1, 0])
theta = np.radians(45) #回転角をラジアンで表示する

R = np.array([
    [np.cos(theta), -np.sin(theta) ],
    [np.sin(theta), np.cos(theta) ]
])
 #回転後のベクトルを計算
v_rotated = R @ v

print(v)
print(v_rotated)

[1 0]
[0.70710678 0.70710678]


##単位行列の計算
単位行列$E$は、ある行列にかけても元の行列は変化しないという性質を持つ。

In [9]:
E = np.array([[1, 0],[0, 1]])
R = np.array([[3, 4],[5, 6]])
print(E @ R)
print(R @ E)

[[3 4]
 [5 6]]
[[3 4]
 [5 6]]


実行結果より、単位行列の計算結果が元の行列Rと完全に一致していることがわかる。
よって
$$単位行列E= \begin {pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix}$$
と任意の行列
$$R = \begin{pmatrix} a & b \\ c & d \end{pmatrix}$$
の積は
$$RE = ER = R$$
となる。

##転置行列
行列の行と列を入れ替えた行列のことを転置行列という。
$$A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{pmatrix} \implies A^T = \begin{pmatrix} 1 & 3 & 5 \\ 2 & 4 & 6\end{pmatrix}$$

In [10]:
A = np.array([['a', 'b'],['c', 'd'],['e', 'f']])
print(A.T)
print()
print('np.transposeによる実行')
#np.transpose(A)でも可能
print(np.transpose(A))

[['a' 'c' 'e']
 ['b' 'd' 'f']]

np.transposeによる実行
[['a' 'c' 'e']
 ['b' 'd' 'f']]


また、以下も成り立つ
$$(AB)^T = B^TA^T$$
しかし、$$(AB^T) = A^TB^T$$
は一般には成り立たない

In [11]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print ((A @ B).T)
print (B.T @ A.T)
if ((A @ B).T == (B.T @ A.T)).all():
  print('これらは等しい')
else :
  print ('これらは等しくない')
print()
print('A^TB^Tの計算')
print (A.T @ B.T)
if ((A @ B).T == (A.T @ B.T)).all():
  print('これらも等しい')
else :
  print('これらは等しくない')

[[19 43]
 [22 50]]
[[19 43]
 [22 50]]
これらは等しい

A^TB^Tの計算
[[23 31]
 [34 46]]
これらは等しくない


##連立方程式とその関係
連立方程式を行列で書き表すことができる
$$\begin{cases} a_{11}x_1 + a_{12} x_2 = y_1 \\ a_{21}x_1+ a_{22}x_2 =y_2 \end{cases}$$
という連立方程式は、行列を用いて
$$\begin{pmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{pmatrix}\begin{pmatrix} x_1 \\ x_2 \end{pmatrix} = \begin{pmatrix} y_1 \\ y_2\end{pmatrix}$$
と表される。

In [12]:
A = np.array([[1, 2], [3, 4]]) #行列
X = np.array([10, 20]) #ベクトル
print(A @ X)


[ 50 110]


##行列式
**行列式**(determinant)は2行2列の場合以下のように定義される。
$$A = \begin{pmatrix} a & b \\ c & d \end{pmatrix}$$
の場合
$$det A = ad - bc$$
なお、行列式は$$det A$$
$$|A|$$
などと表す。

In [13]:
A = np.array ([[1, 2], [3, 4]])
det_A = np.linalg.det(A)
print(round(det_A)) #行列式を四捨五入して整数で表示するコード：round

-2


また、行列式と連立方程式を用いることによって、解がただ一つに決まるかどうかも判定することができる。
連立方程式の行列Aの行列式の値が
$$det A ≠ 0 $$
の場合は、連立方程式の解がただ一つに定まる。

次に3行3列の行列式を考えてみる。
3行3列の行列Aを以下のように定める。
$$A = \begin{pmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33} \end{pmatrix}$$
このとき
$$a_{1σ}$$$$a_{2σ}$$$$a_{3σ}$$
として、それぞれのσに1,2,3のうちから一つずつ対応させ、並べ替えたものをまず考える。
例えば、$a_{11}$,$a_{22}$,$a_{33}$である。
このようにした時、σにそれぞれ対応したものをまとめて$sgn(1,2,3)$と書くとする。
ただし、$sgn(1,1,2)$などのように、同じ数が重複するのは考えない。
さらに以下の通り定義する。
* $sgn(1.2.3)$を入れ替えた形式を考える。その時、一度に2つの数字を入れ替える作業を一回とカウントする。
* 入れ替えたカウント回数が奇数の場合、$sgn$の値を-1とし、偶数の場合1とする
* $det A$を$sgna_{1σ}a_{2σ}a_{3σ}$を一つの項としてすべての項を足し合わせたものとする。

行列A(3行3列)では、定義から
$$sgn(1,2,3)= 1,sgn(1,3,2) = -1, sgn(2,1,3) = -1,\quad sgn(2,3,1) = 1, sgn(3,1,2) = 1, sgn(3,2,1) = -1$$
のようになる。
よって$$detA = a_{11}a_{22}a_{33} + a_{12}a_{23}a_{31} + a_{13}a_{21}a_{32} - a_{11}a_{23}a_{32} -a_{12}a_{21}a_{33} -a_{13}a_{22}a_{31}$$
したがって、3行3列の行列式が導かれた。

実はサラスの公式というものがあり、そちらを使えば簡単に求めることができる。
今導かれた式はサラスの公式そのものである。
しかし、サラスの公式は3行3列限定のものである。
以上で述べた導出は、より一般的なn行n列においても考えることができることがメリットであり、余因子分解の方法でも行列式は求めることが可能である。

In [14]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
det_A = np.linalg.det(A)
print(det_A)
#実際に計算してみる(サラスの公式）
print("実際にサラスの公式で計算してみると")
det_B = 1 * 5 * 9+ 2 * 6 * 7 + 3 * 4 * 8 - 3 * 5 * 7 - 2 * 4 * 9 - 1 * 6 * 8
print(det_B)
if {det_A == det_B}: print (True)
else :
  print(False)

0.0
実際にサラスの公式で計算してみると
0
True


##行列式の性質
単位行列$E$の行列式は1となる
$$ det E_n = 1$$
また、行列$A$の行列式とその転置行列$A^T$の行列式は等しくなる
$$det A = det A^T$$

In [15]:
E = np.array ([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
det_E = np.linalg.det(E)
det_int = int(round(det_E)) #整数のみでの表示
print(det_int)

1


In [16]:
A = np.array([[1, 2,],[3, 4]])
A_T = A.T
det_A_T = np.linalg.det(A_T) #np.arrayは不要（行列の転置だけで計算は発生していないため）
det_int = int(round(det_A_T))
print(det_int)

-2


###上三角行列の行列式
上三角行列の行列式は対角成分の積に等しい
$$det A = \prod_{i=1}^{n}a_ii$$

In [35]:
A = np.array([[3,3,3],[0,5,5],[0, 0, 6]])
det_A = np.linalg.det(A)
print(round(det_A))
print("実際に対角成分を計算してみる")
print(f"{3 * 5 * 6 = }") #f"{ = }"の形で計算式と答えを同時に出力可能
#専用のコードもある
print("ここからはpythonの専用コードで計算してみた結果")
diag_elements = np.diag(A) #対角成分を取り出す
expr_str = " * ".join(map(str, diag_elements))
prod_result = np.prod(diag_elements) #対角成分の計算結果
print(f"{expr_str} = {prod_result}") #計算結果の出力


90
実際に対角成分を計算してみる
3 * 5 * 6 = 90
ここからはpythonの専用コードで計算してみた結果
3 * 5 * 6 = 90
