<a href="https://colab.research.google.com/github/math288/math288.github.io/blob/main/math01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#線形代数の計算

###ベクトルの計算

In [28]:
import numpy as np
A = np.array([1,2,2]) #ベクトルなので、1次元配列で[]一つだけ
B = np.array([3,4,5])
print (A @ B)

21


###行列の足し算

In [29]:
import numpy as np

# 行列 A と B を定義します
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# 行列の足し算
C = A + B

print("行列 A:")
print(A)
print("\n行列 B:")
print(B)
print("\n行列の足し算結果 (A + B):")
print(C)

行列 A:
[[1 2]
 [3 4]]

行列 B:
[[5 6]
 [7 8]]

行列の足し算結果 (A + B):
[[ 6  8]
 [10 12]]


In [30]:
#行列AとBの定義
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6], [7, 8]])

#行列の足し算
C = A + B

print ("行列A:")
print (A)
print ("行列B:")
print (B)
print ("行列A + Bの計算結果　行列C:")
print (C)

行列A:
[[1 2]
 [3 4]]
行列B:
[[5 6]
 [7 8]]
行列A + Bの計算結果　行列C:
[[ 6  8]
 [10 12]]


###行列のスカラー倍

In [31]:
A = np.array([[1,2], [3,4]])
print (3*A)

[[ 3  6]
 [ 9 12]]


###ゼロ行列の計算

In [32]:
A = np.array([[3,5], [3,6]])
O = np.array([[0,0], [0,0]])  #ゼロ行列を定義（すべての成分がゼロの行列）
print (A + O)

[[3 5]
 [3 6]]


###行列の積

In [33]:
A = np.array([[3, 5], [8, 2]])
B = np.array([[1, 2], [3, 4]])
print (A * B) #これはアダマール積
print (A @ B) #行列の積

[[ 3 10]
 [24  8]]
[[18 26]
 [14 24]]


##射影の基本

In [34]:
import numpy as np
A = np.array([3,4])
B = np.array([4,4])
X = A @ B
Y = B @ B
print ((X/Y) * B)



[3.5 3.5]


###ベクトルの回転
ベクトルvの回転後のベクトルv'は、二次元かつ反時計回りの場合、以下のような行列をかけることで求めることができる。

$$R =\begin{pmatrix} \cos\theta & -\sin\theta \\ \sin\theta & \cos\theta \end{pmatrix}$$

この導出を行う。
x座標とy座標を持つ関数のグラフを考え、ある任意の点(a, b) をとる。
その時の点までの距離をr、角度を$\alpha$とする。
すると、 $$a = r\cos\alpha　---①$$
$$b = r\sin\alpha　---②$$
と書くことができる。
$\theta$だけ回転した後の点の座標を(a', b')とすると、
$$a' = r\cos(\alpha + \theta)$$
$$b' = r\sin(\alpha + \theta)$$
となる。
ここで**加法定理**を用いることで以下が導き出せる。
$$a'
= r\cos(\alpha + \theta)
= r(\cos\alpha \cos\theta - \sin\alpha \sin\theta)
=(r\cos\alpha) \cos\theta - (r\sin\alpha)\sin\theta$$
$$b'
= r(\sin\alpha \cos\theta + \cos\alpha \sin\theta=(r\sin\alpha)\cos\theta + (r\cos\alpha)\sin\theta $$
①と②からこれらの式は
$$a' = a\cos\theta - b\sin\theta$$
$$b' = a\sin\theta + b\cos\theta$$
よって、これらを行列とベクトルの積として、移動後のベクトルは
$$\begin{pmatrix} \cos\theta & -\sin\theta \\\sin\theta & \cos\theta\end{pmatrix} \begin{pmatrix} a \\ b\end{pmatrix}
= \begin{pmatrix}  a'\\ b'\end {pmatrix}$$
よって、導出ができた。

In [35]:
v = np.array([1, 0])
theta = np.radians(45) #回転角をラジアンで表示する

R = np.array([
    [np.cos(theta), -np.sin(theta) ],
    [np.sin(theta), np.cos(theta) ]
])
 #回転後のベクトルを計算
v_rotated = R @ v

print(v)
print(v_rotated)

[1 0]
[0.70710678 0.70710678]


###単位行列の計算
単位行列$E$は、ある行列にかけても元の行列は変化しないという性質を持つ。

In [36]:
E = np.array([[1, 0],[0, 1]])
R = np.array([[3, 4],[5, 6]])
print(E @ R)
print(R @ E)

[[3 4]
 [5 6]]
[[3 4]
 [5 6]]


実行結果より、単位行列の計算結果が元の行列Rと完全に一致していることがわかる。
よって
$$単位行列E= \begin {pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix}$$
と任意の行列
$$R = \begin{pmatrix} a & b \\ c & d \end{pmatrix}$$
の積は
$$RE = ER = R$$
となる。

###転置行列
行列の行と列を入れ替えた行列のことを転置行列という。
$$A = \begin{pmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{pmatrix} \implies A^T = \begin{pmatrix} 1 & 3 & 5 \\ 2 & 4 & 6\end{pmatrix}$$

In [37]:
A = np.array([['a', 'b'],['c', 'd'],['e', 'f']])
print(A.T)
print()
print('np.transposeによる実行')
#np.transpose(A)でも可能
print(np.transpose(A))

[['a' 'c' 'e']
 ['b' 'd' 'f']]

np.transposeによる実行
[['a' 'c' 'e']
 ['b' 'd' 'f']]


また、以下も成り立つ
$$(AB)^T = B^TA^T$$
しかし、$$(AB^T) = A^TB^T$$
は一般には成り立たない

In [60]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print ((A @ B).T)
print (B.T @ A.T)
if ((A @ B).T == (B.T @ A.T)).all():
  print('これらは等しい')
else :
  print ('これらは等しくない')
print()
print('A^TB^Tの計算')
print (A.T @ B.T)
if ((A @ B).T == (A.T @ B.T)).all():
  print('これらも等しい')
else :
  print('これらは等しくない')

[[19 43]
 [22 50]]
[[19 43]
 [22 50]]
これらは等しい

A^TB^Tの計算
[[23 31]
 [34 46]]
これらは等しくない
